name: real_pole_pickoff_shake_clean_upload

task_name: ${name}

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [512, 3]
      type: point_cloud
    agent_pos:
      shape: [10]
      type: low_dim
  action:
    shape: [7]

env_runner: null

dataset:
  _target_: mp1.dataset.metaworld_dataset.MetaworldDataset
  # Edit only this path if the server dataset root differs.
  zarr_path: /home/amax/cqy/MP1/MP1/data/clean_zarr/pole_pickoff_shake_clean.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.2
  max_train_episodes: null
